### ISSUE TITLE
Support for changing the BaseURL for all API Calls

### ISSUE THREAD

**Issue by kand617** [apimatic/apimatic-cli#1]
It would be great if we can add support to change the API server that gets called. e.g stable.apimatic.io

**Comment by shahidkhaliq** [comment]
Support for this has been added in the latest version. You can specify an alternate APIMatic code generation server now. Here are a few examples of it's usage:

`apimatic-cli --api https://staging.apimatic.io/api validate fromkey --api-key %APIMATIC_KEY%`
`apimatic-cli --api https://stable.apimatic.io/api validate fromkey --api-key %APIMATIC_KEY%`
`apimatic-cli --api https://apimatic.io/api validate fromkey --api-key %APIMATIC_KEY%`

The last one is equivalent to the default version of the command when no --api option has been specified. Note that you have to provide the **full** base URL for the API.
