### ISSUE TITLE
Add linting and prettier

### ISSUE THREAD

**Issue by safeerraees** [apimatic/apimatic-cli#16]

**Comment by safeerraees** [comment]
Need to add Husky pre-commit hook to run commands like lint and prettier

**Comment by thehappybug** [comment]
Added Husky pre-commit hook in https://github.com/apimatic/apimatic-cli/commit/41e91b835fc5006776a900daa862983050a87c9b. Prettier runs as expected; however, linting has been disabled on pre-commit for now because there are existing lint issues that need to be resolved.
